In [2]:
# Import Libraries
import numpy as np
import pandas as pd

In [3]:
import warnings
warnings.filterwarnings("ignore")

Pre-Processing Steps

In [12]:
# Creating the Dataframe
df=pd.read_csv('/content/Dataset .csv')
df.head(1)

Restaurant ID   Restaurant Name  Country Code         City  \
0        6317637  Le Petit Souffle           162  Makati City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   

                                    Locality  \
0  Century City Mall, Poblacion, Makati City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   

                     Cuisines  ...          Currency Has Table booking  \
0  French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  

[1 rows x 21 columns]

In [13]:
# Droping un-necessary Columns
columns_to_drop = [
    'Restaurant ID', 'Country Code', 'City', 'Address', 'Locality',
    'Locality Verbose', 'Longitude', 'Latitude', 'Currency',
    'Has Table booking', 'Has Online delivery', 'Is delivering now',
    'Switch to order menu', 'Price range', 'Aggregate rating',
    'Rating color', 'Rating text', 'Votes'
]
df.drop(columns=columns_to_drop, inplace=True)

In [15]:
df

Restaurant Name                          Cuisines  \
0             Le Petit Souffle        French, Japanese, Desserts   
1             Izakaya Kikufuji                          Japanese   
2       Heat - Edsa Shangri-La  Seafood, Asian, Filipino, Indian   
3                         Ooma                   Japanese, Sushi   
4                  Sambo Kojin                  Japanese, Korean   
...                        ...                               ...   
9546               Naml۱ Gurme                           Turkish   
9547              Ceviz A��ac۱   World Cuisine, Patisserie, Cafe   
9548                     Huqqa            Italian, World Cuisine   
9549               A���k Kahve                   Restaurant Cafe   
9550  Walter's Coffee Roastery                              Cafe   

      Average Cost for two  
0                     1100  
1                     1200  
2                     4000  
3                     1500  
4                     1500  
...                    ...  
9546                    80  
9547                   105  
9548                   170  
9549                   120  
9550                    55  

[9551 rows x 3 columns]

In [16]:
# Checking for missing values
df.isnull().sum()

Restaurant Name         0
Cuisines                9
Average Cost for two    0
dtype: int64

In [17]:
df.dropna(inplace=True)

In [18]:
df.shape

(9542, 3)

In [19]:
# Checking missing vaalues for each col
missing_values = df.isna().sum()
missing_values_column = df['Restaurant Name'].isna().sum()
missing_values_column = df['Cuisines'].isna().sum()
missing_values_column = df['Average Cost for two'].isna().sum()

In [20]:
df_cleaned = df.dropna()
df_cleaned = df.dropna(subset=['Restaurant Name'])
df_cleaned = df.dropna(subset=['Cuisines'])
df_cleaned = df.dropna(subset=['Average Cost for two'])

In [21]:
df.describe(include="all")

Restaurant Name      Cuisines  Average Cost for two
count              9542          9542           9542.000000
unique             7437          1825                   NaN
top     Cafe Coffee Day  North Indian                   NaN
freq                 83           936                   NaN
mean                NaN           NaN           1200.326137
std                 NaN           NaN          16128.743876
min                 NaN           NaN              0.000000
25%                 NaN           NaN            250.000000
50%                 NaN           NaN            400.000000
75%                 NaN           NaN            700.000000
max                 NaN           NaN         800000.000000

In [22]:
# Converting Categorical data to NUmerical
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
df['Restaurant Name'] = label_encoder.fit_transform(df['Restaurant Name'])
df['Cuisines'] = label_encoder.fit_transform(df['Cuisines'])

In [23]:
df

Restaurant Name  Cuisines  Average Cost for two
0                3742       920                  1100
1                3167      1111                  1200
2                2892      1671                  4000
3                4700      1126                  1500
4                5515      1122                  1500
...               ...       ...                   ...
9546             4436      1813                    80
9547             1310      1824                   105
9548             3063      1110                   170
9549              512      1657                   120
9550             7231       331                    55

[9542 rows x 3 columns]

Building Random Forest Model

In [24]:
# Create X and Y
X = df[['Restaurant Name', 'Average Cost for two']]
Y = df['Cuisines']

In [25]:
from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()

scaler.fit(X)
X= scaler.transform(X)

In [26]:
from sklearn.model_selection import train_test_split

#Split the data into test and train
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2,
                                                    random_state=10)

In [27]:
# predicting using Decision Tree Classifier.
from sklearn.tree import DecisionTreeClassifier

model_DT = DecisionTreeClassifier(random_state=10,
                                   criterion="gini")

# fit the model on data and predict the values
model_DT.fit(X_train,Y_train)      # fit is the function that is used for training the data
Y_pred = model_DT.predict(X_test) # Validation Data
#print(Y_pred)
print(list(zip(Y_test,Y_pred)))

[(1348, np.int64(1348)), (1329, np.int64(1611)), (1608, np.int64(1235)), (1650, np.int64(1655)), (1306, np.int64(1749)), (1514, np.int64(549)), (168, np.int64(50)), (331, np.int64(1424)), (1723, np.int64(1723)), (582, np.int64(865)), (682, np.int64(682)), (1306, np.int64(1329)), (159, np.int64(1098)), (201, np.int64(1306)), (1306, np.int64(1306)), (58, np.int64(58)), (1520, np.int64(546)), (1597, np.int64(1381)), (774, np.int64(765)), (518, np.int64(497)), (1626, np.int64(1626)), (1306, np.int64(1714)), (1749, np.int64(331)), (1520, np.int64(186)), (546, np.int64(684)), (1514, np.int64(1306)), (1334, np.int64(684)), (1212, np.int64(518)), (958, np.int64(1444)), (986, np.int64(986)), (1306, np.int64(1626)), (1256, np.int64(177)), (177, np.int64(518)), (58, np.int64(58)), (1626, np.int64(1626)), (1288, np.int64(1650)), (1514, np.int64(1514)), (12, np.int64(1813)), (497, np.int64(497)), (1306, np.int64(1444)), (233, np.int64(1792)), (1554, np.int64(1765)), (828, np.int64(331)), (1559, np.

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         1
           6       0.25      0.14      0.18         7
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          16       1.00      1.00      1.00         2
          18       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         2
          24       0.00      0.00      0.00  

Building Logistic Regression

In [30]:
from sklearn.linear_model import LogisticRegression
#create a model object
classifier = LogisticRegression(multi_class="multinomial")
#train the model object
classifier.fit(X_train,Y_train)

Y_pred = classifier.predict(X_test)
print(Y_pred)

[1306 1306 1306 ... 1306 1306 1306]


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification report: 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         7
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          11       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          13       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          16       0.00      0.00      0.00         2
          18       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         1
          21       0.00      0.00      0.00         2
          26       0.00      0.00      0.00  